# Generated by Django 4.1.4 on 2023-02-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_company', '0012_alter_headcompany_owner'),
        ('projects', '0003_project_company_head_project_company_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('company removed'), related_name='project_head', to='user_company.headcompany'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('company removed'), related_name='project_po', to='user_company.headcompany'),
        ),
    ]
