# Generated by Django 4.1.4 on 2023-02-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_company', '0013_alter_headcompany_owner_alter_pocompany_owner'),
        ('projects', '0004_alter_project_company_head_alter_project_company_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_head', to='user_company.headcompany'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_po', to='user_company.headcompany'),
        ),
    ]
