# Generated by Django 4.1.4 on 2023-02-07 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_project_company_head_alter_project_company_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='project', to=settings.AUTH_USER_MODEL),
        ),
    ]
