# Generated by Django 4.1.4 on 2023-02-07 10:47

import apps.projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, validators=[apps.projects.validators.validate_project_name]),
        ),
    ]
