# Generated by Django 4.1.4 on 2023-01-26 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcompany',
            name='employees',
            field=models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
