# Generated by Django 4.1.4 on 2023-02-03 07:57

import apps.auth_reg.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_company', '0004_rename_industry_headcompany_client_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocompany',
            name='industry_choice',
            field=models.TextField(max_length=400, validators=[apps.auth_reg.validators.validate_list_industry]),
        ),
    ]
