# Generated by Django 4.1.4 on 2023-02-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_company', '0005_alter_pocompany_industry_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocompany',
            name='start_project',
            field=models.CharField(choices=[('This month', 'This month'), ('In a month', 'In a month'), ('In three month time', 'In three month time'), ('Yesterday', 'Yesterday')], max_length=19),
        ),
    ]
