# Generated by Django 4.1.4 on 2023-02-03 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_company', '0006_alter_pocompany_start_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headcompany',
            name='industry_choice',
            field=models.TextField(max_length=400, validators=[django.core.validators.RegexValidator(message='Invalid characters, the string should start with letters (A-Z) only and can be used symbols ().', regex='^[a-zA-Z]+[a-zA-Z()\\s]*$')]),
        ),
    ]
