# Generated by Django 4.1.4 on 2023-02-06 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_company', '0009_headcompany_is_active_headcompany_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headcompany',
            name='employees',
        ),
        migrations.AddField(
            model_name='headcompany',
            name='employees',
            field=models.ManyToManyField(null=True, related_name='companies_head', to=settings.AUTH_USER_MODEL),
        ),
    ]
