# Generated by Django 4.1.4 on 2023-02-06 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_company', '0010_remove_headcompany_employees_headcompany_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headcompany',
            name='employees',
            field=models.ManyToManyField(related_name='companies_head', to=settings.AUTH_USER_MODEL),
        ),
    ]
