# Generated by Django 4.1.4 on 2023-02-07 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_company', '0012_alter_headcompany_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headcompany',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pocompany',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_po', to=settings.AUTH_USER_MODEL),
        ),
    ]
